{% set name = "langsmith" %}
{% set version = "0.0.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a998bbb2514951c6f7718a9bd426917eb95d694d9cfa2bfda54ab348d6c038f1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - langsmith = langsmith.cli.main:main

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python
    - pydantic >=1.0.0,<3.0.0
    - requests >=2.0.0,<3.0.0

test:
  imports:
    - langsmith
    - langsmith.schemas
    - langsmith.client
  commands:
    - pip check
    - langsmith -h
  requires:
    - pip

about:
  home: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com/
  dev_url: https://github.com/langchain-ai/langsmith-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
