{% set name = "langsmith" %}
{% set version = "0.4.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fb3729e22bd9a225391936cb9d1080322e6c375bb776514af06b56d6c46ed3e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - pydantic >=1,<3
    - requests >=2.0.0
    - orjson >=3.9.14  # [python_impl !='pypy']
    - httpx >=0.23.0,<1
    - requests-toolbelt >=1.0.0
    - zstandard >=0.23.0
    - packaging >=23.2
  run_constrained:
    - langsmith-pyo3 >=0.1.0
    - opentelemetry-sdk >=1.30.0
    - opentelemetry-api>=1.30.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0
    - openai-agents >=0.0.3
    - vcrpy >=7.0.0

# ERROR tests/integration_tests - ModuleNotFoundError: No module named 'vcr'
# vcrpy 7.0.0 is not available in main channel
{% set ignore_tests = " --ignore=tests/integration_tests" %}
# E   ModuleNotFoundError: No module named 'langchain_core'
# cycle dependency langsmith <-> langchain_core. Try during next version bump.
# https://github.com/AnacondaRecipes/langchain-core-feedstock/blob/main/recipe/meta.yaml#L24
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/evaluation/test_runner.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/test_run_helpers.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/test_client.py" %}
# E   openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
{% set ignore_tests = ignore_tests + " --ignore=tests/external/test_instructor_evals.py" %}
# E requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.smith.langchain.com/datasets?limit=1&name=None.tests.evaluation.test_evaluation
{% set ignore_tests = ignore_tests + " --ignore=tests/evaluation/test_evaluation.py" %}

test:
  source_files:
    - tests
  imports:
    - langsmith
    - langsmith._expect
    - langsmith._internal
    - langsmith.anonymizer
    - langsmith.async_client
    - langsmith.beta._evals
    - langsmith.client
    - langsmith.env
    - langsmith.evaluation
    - langsmith.middleware
    - langsmith.run_helpers
    - langsmith.run_trees
    - langsmith.schemas
    - langsmith.utils
    - langsmith.wrappers
  requires:
    - pip
    - pytest >=7.0.0
    - opentelemetry-sdk >=1.30.0
    - opentelemetry-api>=1.30.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0
    - anthropic
    - pytest-tornasync
    - dataclasses-json
    - multipart
    - attrs
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ ignore_tests }}

about:
  home: https://smith.langchain.com
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com
  dev_url: https://github.com/langchain-ai/langsmith-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
