{% set name = "langsmith" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b60f1785aed4dac5e01f24db01aa18fa1af258bad4531e045e739438daa3f8c2

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - httpx >=0.23.0,<1
    - orjson >=3.9.14
    - packaging >=23.2
    - pydantic >=2,<3
    - requests >=2.0.0
    - requests-toolbelt >=1.0.0
    - uuid-utils >=0.12.0,<1.0
    - zstandard >=0.23.0
  run_constrained:
    - langsmith-pyo3 >=0.1.0rc2,<0.2.0
    - rich >=13.9.4
    - pytest >=7.0.0
    - openai-agents >=0.0.3,<0.1
    - opentelemetry-sdk >=1.30.0,<2.0.0
    - opentelemetry-api >=1.30.0,<2.0.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0,<2.0.0
    - claude-agent-sdk>=0.1.0  # [py>=310]

# ERROR tests/integration_tests - ModuleNotFoundError: No module named 'vcr'
# vcrpy 7.0.0 is not available in main channel
{% set ignore_tests = " --ignore=tests/integration_tests" %}
# E   ModuleNotFoundError: No module named 'langchain_core'
# cycle dependency langsmith <-> langchain_core. Try during next version bump.
# https://github.com/AnacondaRecipes/langchain-core-feedstock/blob/main/recipe/meta.yaml#L24
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/evaluation/test_runner.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/test_run_helpers.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/test_client.py" %}
# E   openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
{% set ignore_tests = ignore_tests + " --ignore=tests/external/test_instructor_evals.py" %}
# E requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.smith.langchain.com/datasets?limit=1&name=None.tests.evaluation.test_evaluation
{% set ignore_tests = ignore_tests + " --ignore=tests/evaluation/test_evaluation.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/test_uuid_v7.py" %}  # [win]
# dataclasses-json is not available in main channel for Python 3.14.
{% set ignore_tests = ignore_tests + " --ignore=tests/unit_tests/test_utils.py" %}  # [py<314]


test:
  source_files:
    - tests
  imports:
    - langsmith
    - langsmith._expect
    - langsmith._internal
    - langsmith.anonymizer
    - langsmith.async_client
    - langsmith.beta._evals
    - langsmith.client
    - langsmith.env
    - langsmith.evaluation
    - langsmith.middleware
    - langsmith.run_helpers
    - langsmith.run_trees
    - langsmith.schemas
    - langsmith.utils
    - langsmith.wrappers
  requires:
    - pip
    - pytest >=7.0.0
    - opentelemetry-sdk >=1.30.0
    - opentelemetry-api>=1.30.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0
    - anthropic >=0.45.0
    - pytest-tornasync
    # dataclasses-json is not maintained anymore and not available in main channel for Python 3.14.
    - dataclasses-json  # [py<314]
    - multipart
    - attrs
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ ignore_tests }}

about:
  home: https://smith.langchain.com
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com
  dev_url: https://github.com/langchain-ai/langsmith-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
