{% set name = "langsmith" %}
{% set version = "0.1.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/langchain-ai/langsmith-sdk/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b84646c6972719927bb44ce0d8f1f0753b90cefa3a3a99b112be7ac1ec7683c3
  
build:
  number: 0
  script: {{ PYTHON }} -m pip install ./python --no-deps --no-build-isolation -vv
  entry_points:
    - langsmith = langsmith.cli.main:main

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python
    - pydantic >=1.0.0,<3.0.0
    - requests >=2.0.0,<3.0.0
    - orjson >=3.9.14,<4.0.0

test:
  imports:
    - langsmith
    - langsmith.schemas
    - langsmith.client
  requires:
    - pip
  commands:
    - pip check
    - langsmith -h

about:
  home: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com/
  dev_url: https://github.com/langchain-ai/langsmith-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
  skip-lints:
    - missing_wheel
