{% set name = "langsmith" %}
{% set version = "0.1.129" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/langchain-ai/langsmith-sdk/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ca998f11e54ebaf8f1e08d6294a7fe7d058949a76d28eca54984436a3ec52666
  
build:
  skip: True  # [py<38 or s390x]
  number: 0
  script: {{ PYTHON }} -m pip install ./python --no-deps --no-build-isolation -vv
  entry_points:
    - langsmith = langsmith.cli.main:main

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - httpx >=0.23.0,<1
    - python
    - pydantic >=1.0.0,<3.0.0
    - requests >=2.0.0,<3.0.0
    - orjson >=3.9.14,<4.0.0

test:
  source_files:
    - python/tests
    - python/pyproject.toml
  imports:
    - langsmith
    - langsmith.schemas
    - langsmith.client
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-rerunfailures
    - attrs
    - dataclasses-json
  commands:
    - pip check
    # Requires dependent package langchain
    {% set tests_to_skip = "test_as_runnable" %}
    # Requires building from git repository
    {% set tests_to_skip = tests_to_skip + " or test_git_info" %}
    # Test labeled as flaky by upstream, but consistently fails on aarch64.
    {% set tests_to_skip = tests_to_skip + " or test_client_gc" %}  # [aarch64]
    # Requires dataclasses-json
    - pytest python/tests/unit_tests -k "not ({{ tests_to_skip }})"

about:
  home: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com/
  dev_url: https://github.com/langchain-ai/langsmith-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
  skip-lints:
    - missing_wheel
